#!/bin/bash

set -e

mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe --labels=Before --stoponerror --workers=1 --inprocess --trace=Debug src/Infrastructure.Tests/bin/Debug/Infrastructure.Tests.dll
mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe --labels=Before --stoponerror --workers=1 --inprocess --trace=Debug src/Consensus.Tests/bin/Debug/Consensus.Tests.dll
mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe --labels=Before --stoponerror --workers=1 --inprocess --trace=Debug src/Consensus.Features.Tests/bin/Debug/Consensus.Features.Tests.dll
mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe --labels=Before --stoponerror --workers=1 --inprocess --trace=Debug src/Blockchain.Tests/bin/Debug/Blockchain.Tests.dll
mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe --labels=Before --stoponerror --workers=1 --inprocess --trace=Debug src/Wallet.Tests/bin/Debug/Wallet.Tests.dll
mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe --labels=Before --stoponerror --workers=1 --inprocess --trace=Debug src/Network.Tests/bin/Debug/Network.Tests.dll
