#!/bin/bash

set -e

function run {
    mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe --labels=Before --stoponerror --workers=1 --inprocess --trace=Debug $1
}

run src/Node.Tests/bin/Debug/Node.Tests.dll
run src/Zulib.Tests/bin/Debug/Zulib.Tests.dll
run src/Infrastructure.Tests/bin/Debug/Infrastructure.Tests.dll
run src/Consensus.Tests/bin/Debug/Consensus.Tests.dll
run src/Consensus.Features.Tests/bin/Debug/Consensus.Features.Tests.dll
run src/Blockchain.Tests/bin/Debug/Blockchain.Tests.dll
run src/Wallet.Tests/bin/Debug/Wallet.Tests.dll
run src/AddressDB.Tests/bin/Debug/AddressDB.Tests.dll
run src/Network.Tests/bin/Debug/Network.Tests.dll

